# Generated by Django 4.1.3 on 2022-11-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='resourcescategory',
            old_name='CategoryDescription',
            new_name='Category_description',
        ),
        migrations.RenameField(
            model_name='resourcescategory',
            old_name='CategoryName',
            new_name='category_designation',
        ),
        migrations.RenameField(
            model_name='resourcescategory',
            old_name='CategoryOccupation',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='profiles',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='linkdin_profile',
            field=models.URLField(),
        ),
    ]
